// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGTNPSLFOA2WMG_0tpXl1R5Bw4IyZwy8g',
    appId: '1:1074500372330:web:e261d589947021c3d1c713',
    messagingSenderId: '1074500372330',
    projectId: 'astroapp-9386d',
    authDomain: 'astroapp-9386d.firebaseapp.com',
    storageBucket: 'astroapp-9386d.appspot.com',
    measurementId: 'G-9PTV1ZL6RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0XKsN3cVE8g8rH9ctU4ovBc7fBSbczDA',
    appId: '1:1074500372330:android:a550c1ad3b5646ced1c713',
    messagingSenderId: '1074500372330',
    projectId: 'astroapp-9386d',
    storageBucket: 'astroapp-9386d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbHyhIFG316A7uY4Xsfz15fmzGca2K6n4',
    appId: '1:1074500372330:ios:bebeb95d4930d51ad1c713',
    messagingSenderId: '1074500372330',
    projectId: 'astroapp-9386d',
    storageBucket: 'astroapp-9386d.appspot.com',
    iosBundleId: 'com.example.astroapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbHyhIFG316A7uY4Xsfz15fmzGca2K6n4',
    appId: '1:1074500372330:ios:bebeb95d4930d51ad1c713',
    messagingSenderId: '1074500372330',
    projectId: 'astroapp-9386d',
    storageBucket: 'astroapp-9386d.appspot.com',
    iosBundleId: 'com.example.astroapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGTNPSLFOA2WMG_0tpXl1R5Bw4IyZwy8g',
    appId: '1:1074500372330:web:87240e2f5412dc98d1c713',
    messagingSenderId: '1074500372330',
    projectId: 'astroapp-9386d',
    authDomain: 'astroapp-9386d.firebaseapp.com',
    storageBucket: 'astroapp-9386d.appspot.com',
    measurementId: 'G-V3V5E9B1JZ',
  );
}
